#!/usr/bin/env node
/*
 * Writes (or checks) `vectors/MANIFEST.json` — the list of every vector, so a
 * consumer that copies `vectors/` into another language's test bundle can
 * prove it copied all of them.
 *
 * `--write` regenerates it; `--check` fails when it has drifted from the tree,
 * which is what CI runs. Adding a vector is still "add the JSON file" plus
 * `npm run manifest`.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const vectorsDir = join(root, 'vectors')
const manifestPath = join(vectorsDir, 'MANIFEST.json')

const ids = []
const suites = {}
for (const entry of readdirSync(vectorsDir, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue
  for (const file of readdirSync(join(vectorsDir, entry.name))) {
    if (!file.endsWith('.json')) continue
    const v = JSON.parse(readFileSync(join(vectorsDir, entry.name, file), 'utf8'))
    if (v.suite !== entry.name) {
      console.error(`${entry.name}/${file}: suite field is "${v.suite}"`)
      process.exit(1)
    }
    ids.push(`${v.suite}/${v.id}`)
    suites[v.suite] = (suites[v.suite] ?? 0) + 1
  }
}
ids.sort()

const manifest = {
  note: 'Generated by scripts/manifest.mjs. A consumer that copies vectors/ asserts its loaded set against this, so a dropped file is a failure rather than a smaller green run. It does not detect staleness — for that, compare the pinned commit against upstream.',
  count: ids.length,
  suites: Object.fromEntries(Object.keys(suites).sort().map((s) => [s, suites[s]])),
  vectors: ids,
}
const text = `${JSON.stringify(manifest, null, 2)}\n`

if (process.argv.includes('--check')) {
  let current = null
  try {
    current = readFileSync(manifestPath, 'utf8')
  } catch {
    console.error('vectors/MANIFEST.json is missing — run `npm run manifest`')
    process.exit(1)
  }
  if (current !== text) {
    console.error('vectors/MANIFEST.json has drifted from vectors/ — run `npm run manifest`')
    process.exit(1)
  }
  console.log(`manifest ok: ${manifest.count} vectors`)
} else {
  writeFileSync(manifestPath, text)
  console.log(`wrote vectors/MANIFEST.json: ${manifest.count} vectors`)
}
